Repository albertms10/music_notes, pull requests merged in 2024-05, with the labels that each got.

#491 test(closest_pitch): 🧪 add test cases for `toString` rounding
  README.md
  example/main.dart
  lib/src/note/closest_pitch.dart
  test/src/note/closest_pitch_test.dart
Labels: documentation, test

#492 chore(pubspec): 🚚 use correct `repository` URL
  pubspec.yaml
Labels: enhancement

#470 fix(pitch): 🐛 address large `ClosestPitch` spellings for `harmonics` with `temperature`
  lib/src/note/pitch.dart
  test/src/note/pitch_test.dart
Labels: bug, enhancement, test

#476 feat!(interval): ✨ add `fromSemitones(int)` and rename `fromSizeAndSemitones` factory constructors
  lib/src/interval/interval.dart
  lib/src/interval/interval_class.dart
  lib/src/interval/size.dart
  lib/src/note/note.dart
  lib/src/note/pitch.dart
  test/src/interval/interval_test.dart
  test/src/interval/size_test.dart
Labels: enhancement

#457 refactor(hearing_range): ♻️ rename `isAudibleAt` method
  lib/src/note/frequency.dart
  lib/src/note/hearing_range.dart
Labels: refactor

#499 chore(pubspec): 🏗️ bump Dart SDK 3.4.0
  .github/workflows/analysis-ci.yaml
  lib/src/interval/interval.dart
  pubspec.yaml
Labels: dependencies

#500 chore(analysis_options): 🕵️ enable new lints and fix `unnecessary_library_name`
  .vscode/settings.json
  analysis_options.yaml
  lib/music_notes.dart
Labels: refactor

#501 feat!(scalable): 💥 allow providing `reference` in `numericRepresentation`
  README.md
  example/main.dart
  lib/src/scalable.dart
  test/src/scalable_test.dart
Labels: enhancement, test

#502 feat!(pitch): 💥 use double, triple, and quadruple prime symbols for Helmholtz notation
  README.md
  example/main.dart
  lib/src/note/pitch.dart
  test/src/note/pitch_test.dart
Labels: enhancement, test
